### ISSUE TITLE
Update Script Shortcuts

### ISSUE THREAD

**Issue by Genide** [Oncorporation/CastorLazyPack#4]
Then please update all the script shortcuts. They all still point to **CastorLazyPack**, instead of **CastorrsLazyPack**. This results in an unusable browser source.

![image](https://user-images.githubusercontent.com/10857365/54475957-a9897c80-47c5-11e9-878a-02a653d8deac.png)

C:\Users\SOME_NAME\AppData\Roaming\Streamlabs\Streamlabs Chatbot\Services\Scripts\ **CastorLazyPack**\index.html

_Originally posted by @Genide in https://github.com/Oncorporation/CastorLazyPack/issues/3#issuecomment-473530425_

**Comment by Oncorporation** [comment]
Investigating

**Comment by Oncorporation** [comment]
Ahh, we had reorganized the folder and changed the included settings files. So, this was addressed. Thank you for your report!

**Comment by Oncorporation** [comment]
We did find that the INDEX.HTML FILEPATH did not contain the overlay subfolder path. Thanks to Genide and WalkerTrips for their help solving this issue in version 1.5.3.1
